const WORLD_RANKINGS: Record<string, number> = {
  France: 1,
  Argentina: 2,
  Spain: 3,
  England: 4,
  Portugal: 5,
  Brazil: 6,
  Morocco: 7,
  Netherlands: 8,
  Belgium: 9,
  Germany: 10,
  Croatia: 11,
  Colombia: 13,
  Senegal: 14,
  Mexico: 15,
  'United States': 16,
  Uruguay: 17,
  Japan: 18,
  Switzerland: 19,
  Iran: 20,
  Turkey: 22,
  Austria: 23,
  Ecuador: 24,
  'South Korea': 25,
  Australia: 27,
  Algeria: 28,
  Egypt: 29,
  Canada: 30,
  Norway: 31,
  Panama: 33,
  'Ivory Coast': 34,
  Sweden: 38,
  Paraguay: 40,
  'Czech Republic': 41,
  Scotland: 43,
  'DR Congo': 45,
  Tunisia: 46,
  Uzbekistan: 50,
  Qatar: 55,
  Iraq: 56,
  'South Africa': 60,
  'Saudi Arabia': 61,
  Jordan: 63,
  'Bosnia and Herzegovina': 64,
  'Cape Verde': 68,
  Ghana: 73,
  Haiti: 81,
  Curacao: 83,
  'New Zealand': 85,
}

export function getWorldRanking(teamName: string): number | null {
  return WORLD_RANKINGS[teamName] ?? null
}
